source "https://rubygems.org"

ruby File.read(".ruby-version").strip

gem "axlsx", git: "https://github.com/randym/axlsx.git", ref: "c593a08"
gem "axlsx_rails"
gem "cf-app-utils"
gem "jbuilder", "~> 2.9"
gem "pg", "~> 1.1"
gem "pghero"
gem "puma", "~> 3.12"
gem "pundit"
gem "redcarpet"
gem 'redis-rails'
gem "rubyzip", ">= 1.2.1"
gem 'scout_apm'
gem "slim-rails"
gem "strong_migrations"
gem "wicked"

group :development, :test do
  gem "roo", "~> 2.8.2"
  gem "rspec-mocks"
  gem 'dotenv-rails', require: 'dotenv/rails-now'
  gem "shared-web-dev", path: "../shared-web/dev"
end

gem "shared-web", path: "../shared-web"
